name: Run Challenge Tests

on:
  push:
    paths:
      - '**/solutions.py'
      - '**/tests.json'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run tests for changed challenges
        run: |
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "Changed files:"
          echo "$changed_files"

          changed_dirs=$(echo "$changed_files" | grep -E 'solutions\.py|tests\.json' | cut -d'/' -f1-3 | uniq)
          echo "Changed dirs:"
          echo "$changed_dirs"

          for dir in $changed_dirs; do
            solutions="$dir/solutions.py"
            tests="$dir/tests.json"

            echo "Checking files:"
            echo "solutions: $solutions"
            echo "tests: $tests"

            if [[ -f "$solutions" && -f "$tests" ]]; then
              echo "✅ Running tests in $dir"
              (cd "$dir" && python solutions.py)
            else
              echo "⚠️  Skipping $dir (needs both solutions.py and tests.json)"
            fi
          done
